In [1]:
import qiskit
from math import pi
import numpy as np
import pandas as pd
from math import sqrt
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
from qiskit.visualization.bloch import Bloch
from qiskit.visualization import plot_bloch_vector, plot_bloch_multivector

In [8]:
np.arctan2(1,1)

0.7853981633974483

In [12]:
color_list = []
color_index = []

df = pd.DataFrame(columns=range(1,4))

for i in range(0,256):
  for j in range(0,256):
    for k in range(0,256):

# Normalization
      r, g, b = (i,j,k)
      r, g, b = r/255, g/255,b/255
      r, g, b = 2*(r-0.5) / np.sqrt(3), 2*(g-0.5) / np.sqrt(3),2*(b-0.5) / np.sqrt(3)

# r,g,b to theta,phi
      theta = 2 * np.arctan2( np.sqrt(g**2+b**2), np.sqrt(1-g**2-b**2) )
      phi =  np.arctan2(b,g)-np.arctan2(r, np.sqrt(1.001-g**2-b**2-r**2))
      z = np.cos(theta)
      y = np.sin(theta)*np.sin(phi)
      x = np.sin(theta)*np.cos(phi)
      color_index.append([i,j,k])
      P = np.array([x,y,z])

      color_list.append(P)

color_list

[array([ 0.62920872, -0.7021291 , -0.33333333]),
 array([ 0.56961554, -0.75581933, -0.32291683]),
 array([ 0.53227969, -0.78674686, -0.31258234]),
 array([ 0.50192972, -0.81034758, -0.30232987]),
 array([ 0.47542608, -0.82982704, -0.29215943]),
 array([ 0.45145822, -0.84653495, -0.282071  ]),
 array([ 0.42932907, -0.86119534, -0.27206459]),
 array([ 0.4086151, -0.8742518, -0.2621402]),
 array([ 0.38903596, -0.88600047, -0.25229783]),
 array([ 0.37039463, -0.89665121, -0.24253749]),
 array([ 0.3525463 , -0.9063596 , -0.23285916]),
 array([ 0.33538083, -0.91524499, -0.22326285]),
 array([ 0.31881208, -0.92340154, -0.21374856]),
 array([ 0.30277117, -0.93090519, -0.20431629]),
 array([ 0.28720198, -0.93781835, -0.19496604]),
 array([ 0.27205806, -0.94419317, -0.18569781]),
 array([ 0.25730042, -0.95007376, -0.1765116 ]),
 array([ 0.242896  , -0.95549793, -0.16740741]),
 array([ 0.22881639, -0.9604984 , -0.15838524]),
 array([ 0.21503705, -0.96510374, -0.14944509]),
 array([ 0.20153656, -0

In [9]:
color_list = []
color_index = []

df = pd.DataFrame(columns=range(1,4))

for i in range(0,256):
  for j in range(0,256):
    for k in range(0,256):

# Normalization
      r, g, b = (i,j,k)
      r, g, b = r/255, g/255,b/255
      r, g, b = 2*(r-0.5) / np.sqrt(3), 2*(g-0.5) / np.sqrt(3),2*(b-0.5) / np.sqrt(3)

# r,g,b to theta,phi
      theta = 2 * np.arctan2( np.sqrt(g**2+b**2), np.sqrt(1-g**2-b**2) )
      phi =  np.arctan2(b,g)-np.arctan2(r, np.sqrt(1-g**2-b**2-r**2))
      if g == 0:
        phi = 1.5708-np.arctan2(r, np.sqrt(1-g**2-b**2-r**2))
      elif r == g ==b == 1/ np.sqrt(3):
        phi = -0.785398
      z = np.cos(theta)
      y = np.sin(theta)*np.sin(phi)
      x = np.sin(theta)*np.cos(phi)
      color_index.append([i,j,k])
      P = np.array([x,y,z])

      color_list.append(P)

color_list

C:\Users\HCI\AppData\Local\Temp\ipykernel_19436\3774451252.py:17: RuntimeWarning: invalid value encountered in sqrt
  phi =  np.arctan2(b,g)-np.arctan2(r, np.sqrt(1-g**2-b**2-r**2))


[array([        nan,         nan, -0.33333333]),
 array([ 0.57810522, -0.74934577, -0.32291683]),
 array([ 0.53859114, -0.78243968, -0.31258234]),
 array([ 0.50721331, -0.80705099, -0.30232987]),
 array([ 0.48007342, -0.82714714, -0.29215943]),
 array([ 0.45565836, -0.8442816 , -0.282071  ]),
 array([ 0.43319061, -0.85925942, -0.27206459]),
 array([ 0.41220741, -0.87256379, -0.2621402 ]),
 array([ 0.39240668, -0.88451275, -0.25229783]),
 array([ 0.37357824, -0.89532947, -0.24253749]),
 array([ 0.35556876, -0.90517814, -0.23285916]),
 array([ 0.3382623 , -0.91418396, -0.22326285]),
 array([ 0.32156863, -0.92244521, -0.21374856]),
 array([ 0.30541587, -0.93004086, -0.20431629]),
 array([ 0.28974566, -0.93703559, -0.19496604]),
 array([ 0.2745098 , -0.94348328, -0.18569781]),
 array([ 0.25966798, -0.94942941, -0.1765116 ]),
 array([ 0.24518601, -0.95491287, -0.16740741]),
 array([ 0.23103465, -0.95996724, -0.15838524]),
 array([ 0.21718862, -0.96462183, -0.14944509]),
 array([ 0.2036259 ,

In [10]:
for i in range(32):
    color_space = pd.Series(color_list[524288*i:524288*(i+1)], index = pd.Index(color_index[524288*i:524288*(i+1)]))
    color_space.to_excel(f"color_space{i+1}.xlsx", index=True)